# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [shark, sbabes]
patreon: # Replace with a single Patreon username IHeartRadio
open_collective: # Replace with a single Open Collective username hunterz.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., tor.onion
liberapay: # Replace with a single Liberapay username stone87
issuehunt: # Replace with a single IssueHunt username! Knightlinelegañ
otechie: # Replace with a single Otechie username Morgan & Morgan
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://opensea.io','https://pornhub.com','https://youporn.com','https://Masterclass.com','https://todaysmilitary.gov', 'https://mypillow.com']
